// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLApClUpFPAX4iLc9AekVGeF_U1uaC-g0',
    appId: '1:986237144599:web:2b8c4d0b8458e22d175652',
    messagingSenderId: '986237144599',
    projectId: 'flutterapplication-e8612',
    authDomain: 'flutterapplication-e8612.firebaseapp.com',
    storageBucket: 'flutterapplication-e8612.firebasestorage.app',
    measurementId: 'G-NJR8EJ98BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMLpETu4rWRFtozq0cYRzDQBtsh-Ahzx8',
    appId: '1:986237144599:android:33fc8d78d158ae51175652',
    messagingSenderId: '986237144599',
    projectId: 'flutterapplication-e8612',
    storageBucket: 'flutterapplication-e8612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQ455fQfn7PW2rHDfWUdDx0QFSu0aTOE',
    appId: '1:986237144599:ios:2e747564ca0edf46175652',
    messagingSenderId: '986237144599',
    projectId: 'flutterapplication-e8612',
    storageBucket: 'flutterapplication-e8612.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQ455fQfn7PW2rHDfWUdDx0QFSu0aTOE',
    appId: '1:986237144599:ios:2e747564ca0edf46175652',
    messagingSenderId: '986237144599',
    projectId: 'flutterapplication-e8612',
    storageBucket: 'flutterapplication-e8612.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLApClUpFPAX4iLc9AekVGeF_U1uaC-g0',
    appId: '1:986237144599:web:2f3a0ecf812c9f33175652',
    messagingSenderId: '986237144599',
    projectId: 'flutterapplication-e8612',
    authDomain: 'flutterapplication-e8612.firebaseapp.com',
    storageBucket: 'flutterapplication-e8612.firebasestorage.app',
    measurementId: 'G-9ZL0GE4SBH',
  );
}
